// Auto-generated by build/msdfFontsPlugin.ts.
// Do not edit manually.

export interface BitmapFontAsset {
	family: string;
	url: string;
}

export const BITMAP_FONT_ASSETS: readonly BitmapFontAsset[] = [
	{ family: "Rubik", url: "/assets/fonts/Rubik.fnt" }
];
